---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgBQiEP2Et0dhNIpjpd+gH/gAkFxtsh+xRiDHB/n7YZ2IfpssuH2THgotOWkOXikgDFk9qpLDMIKXqmyGOuRjdhINpQghpYUjRQMJLcAXz9Ty0XT1zKi1e7sBa0q5e5t83+bsHbQLu9jpNOGCPI9MnzqDvzMRBxXSw5JLSLZaOhkT3D1jXBHeljnk2/MFqHvoI8e0fiJZkDZrf7+fTzGtmVECbCyGUD9lzgNHJhAzmPp71cFY0LzGtBfHqpgEI+vAB8xVvJlesOpPW0ra4ggrbyvRLB0vyk+P40mWkPpy1Jc2CnIwpxY+8vouy/pSbrH1A9C8o/vcqI8RTYvXd+XG8qHLWzPFzdvzD7vSKCL7th1MFATeDw7jEkq4TTt5f3yp/QReRhHQ9kkdmb0gkF7ima5dyPrrYCDjOVUZwjUlA9i/xv8kSzkTcZGjo0Ql/YVPsJUzDuqCqXufl/ZXryWU4jvCosx+0RNxLU1xEiyDGVf9KMklLyDlukH9WiI1K9i/nVfhyRT7Dh6E10tCl2ULz6QOcFVH6k2CXjQAk765ajl+AYg0E8vwPqWOAQxdw5drLelHFbuuGc4KqkB9pD4ssRxNzAW+L7vom7aUIWZOXxyiQCrFPoFkBCmzImuzpDULWYjaRahEzdxaYvom+wZYThf1z3bfgX++h8Xj5betn/xmGRcUB4U46OCyRmOytELP+TdSL+p/DOTesMYX7adSlz1XCw6b9ZhPGj/rC3r5gFh7jwRMS2o9veyMr3Wu3JxrJBulhhFgqNs07AlLitZEJbhlnm3BSSgHtA=
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
