---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCB8c+tKd3dbzNgGkHBs3ih/t3I4Ck+D0pDoTUAeD2U0aK4QRX8Sz8ohtl8FbWMBl0z3XjB4jhaUokwf9qLRNt/I+r8ChDp2Ae9E+2sbEhW2D+QteNv0eikMItFyPJtD8jxfFw+fGZJeT45jcnrGGKnkiJ84jZiiWa/zSfzbLWk9Uxo9FjW1iLDO58IyPfywFccaPEwiB3umEzMaYYSRPgctueb125R4tyO7DpuDMKKjfjk1817YfKsOzbv7x9kjWmtz98Y3pUeC7LFzUtd8IyxznD9Z7ImMnjxeZXcICfCdc5hdjQBHixVWejhT8GdhgeaXaMr4/A1S236A5l1nmwsK+HacKNqZsdnhhdwwdKQWxHu91P58n6hjR+P0ADeIlbyRqAXQ978bbtqGa3CwAbbafl5aBuNwUjfydicjfgNxAej/aNJbNMO5IvRaopg9Eg9a4+jEvvP5zCTflMXskoDkjiyviRuIJ02l2kXtfunyYpERGdfySpA2Pv7oPWE1rsiZQO+SMUSfUJJcV0FB67vROdYsS2DxtnnQwPmWnxKD2uTaFLmXqrq5K5OGLRS6Ocg9RfLhinqGaa9SvYTxyrr6O82CongzFMr3EEDaJzoNlmixSBqPGsk/IMi1Wy+TlJD9tF0jxPtWAEZtMyPYuhD4eTfMdhplk2OF3s1uFKLoA2xG04pCb5o/4M7GaRCmzc96+wK65sIEmVfyEXxDv3qVm6XkbzV+VfgyI9U555KKQ==
    admin-user: AgBFIjodbQliyMIM8Kr/SzdxlZnGANaAKO4HYGD4qBOKLpDsX9GcqIbucIMLVXoD6Vplbso/7gf2XKvqe/wNde6owK3ImOhjnOg8H99emSDhTtvrkXaTaO+Smlam9vBgzRARS0HojpdtcIhtmxKYvZYqhyn+ios+MwNstYhq5k1VRqH3HsrAuYSnS8LvdGBkFCFRuo7Liz2FFX4lA6+HY7UwVxuYRO8ucevUA8siR00+5k1cGT0QAwrknpe4kLzCcKT6ka5HWLhmUoTpokGUJ6VSyef9mX+OedQDBqVy1HD/eqjyUQZ/sa641k/aCgHfSdgg4kg45/J5VS9qp3U8jx9cXt0swZPMj5riFFurHEGrr0RCNmIvlp4yqrTBmvHDtney7xv1wNcZ3kAoYNoOqc2iMrHeluPcv/LypFOz+oVrxWc8OvlvCNeYbSq4AQoX6qV1vS7OsTN3KH5/8xDg8WTMM42xBXkRJTt0IAOuIcklhMcMRwt+wDuGGySxcp1s4vmHF4zZD5z3Audl3OPyYIKyd+0BDvDZnYgeVnEKuo3FuZfFZeg0ffNbep1N/yTsvmevgQ4qGJ9OgTFEi1tvP+1S3BgUmeT+CHGhgRbg4g1hFCmGv7oI3z2NbaZTqtUys7KqKqkC/ck1V+DqLPbwAtnLGkWRIELywjzTLSPGrQdVRW2LzmrQgFonGzTdhlPK7YSUooAtGw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
