kubelet:
  enabled: true
  serviceMonitor:
    tlsConfig:
      insecureSkipVerify: true

grafana:
  additionalDataSources:
    - access: proxy
      jsonData:
        maxLines: 1000
      name: Loki
      type: loki
      url: http://loki.loki.svc.cluster.local:3100
  envFromSecrets:
    - name: grafana-oidc
  grafana.ini:
    auth:
      disable_login_form: true
    auth.generic_oauth:
      api_url: https://auth.fivelabs.tech/api/oidc/userinfo
      auth_url: https://auth.fivelabs.tech/api/oidc/authorization
      client_id: grafana
      client_secret: $__env{client_secret}
      empty_scopes: false
      enabled: true
      groups_attribute_path: groups
      login_attribute_path: preferred_username
      name: Authelia
      name_attribute_path: name
      role_attribute_path: contains(groups[*], 'admin') && 'Admin' || 'Viewer'
      scopes: openid profile email groups
      token_url: https://auth.fivelabs.tech/api/oidc/token
      use_pkce: true
    server:
      root_url: https://grafana.fivelabs.tech