---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-creds
  namespace: loki
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB75IfWyg15J6R/VMAkGyoZUYyZlAEp23jcCRBLoCwUH46PJnQFGhOl9aAoLMF2JZjv+O3zbCQI8ucQM4hCSVoQ57f2gwtO4r6pntG4rrB+8tAXwa/OYXYnAwPHLaGDYD/+RCbKOi78WdN4nNwJuIdgC1zHOqQiNMS6DG2GYKfAagQdf76VD6/NnUmWPtMQU0F5TnX+GSMLPts8L/xbbtvT2hVUeIa/t89zWllFYdw22EAqhZOhYOFd9IAU+Broo1+jec59vxUNjF8/rFZoUntI2IlVvFvdS3vtp5pYYgvyku1L2Pd0u8DDTlF0u3Y885qSRzn0xpfS8DiNzg44qqc8lYxX2rud3Ptzb+5vkzmrdbhlLpzzmtvLt4PgfDEgSSZPkfHdfCOn5OviK/JklKKaBMgSDrfFsJVcV9jAIY2CN3XHqWAxQERsCXlYetbIJh9i0jpo7xuZsBxmAtIgMef2XvmyFGPY8vkyF8zw9y56CWpBBGKyYQ/Ur/CgZ9SESBkALTYFvZVd83yL6UqlRgKqcVTha3Vx94IyCyWKhnl/GMIZZuQ0ZYOd6Jz1SXLaL/E+kIJiAxm6sXlNcw28GEm46F8c6XLIjUg4Ws5CDxKj1nctikC6TdcQGgmn08cdr9zKSKt7pgD2O266M7TW9R/tQwzUJeHPTOw5ZVlmePP9SwA8G+YGJ+tu6e8bevbMHPMKkO85dcKSOzJz2z1zylqSV65oYA==
    AWS_SECRET_ACCESS_KEY: AgA6TZM0M9f1vlOP1o8XV0wtHgxxNnTCQRwT4Izqo/6I0KV94g3GAEOBf+2++k2n7egdX0F2MvU8hTUQMm/5oERzb4OXcdbNA+jynETsumfVmdgxJP3hT2uqJ0TKkknbEu7It0LUk8xddq8XXEfBKYkxq939pDMCYTq0dFsbSOGs8iP7GD1Q2RpISnuUQ6gdBbZy/CEDV3XE0uMrKsxFNvEdnvTRX0Mznfnj+ZlSzXAQtLeiOA8Knij5vjK3i6nR5gHzhf08OId1MvoYGPUIzha+d9TY2fJEI+B9n6Bs60RaMUWhAnGHcr6RXxWBDv6bFH23G4zffB0XGzoqUb/ZsP+7+Vx7mkbDXZRG2ZEcAfPx0QdmqlMaO2l9+8/GdCoFUdmvS+BbS6USg+E+9GoJJENY8krQYPoSs6rxCfkZrdEEKWajXhNT9h10bcVVdiL3jiQ64K7mae+gT6cEmBn2bvtKgI6hRApS8fDGfu/edUKVi0GoOstZZglkTCaxvr/LHsRC5tGM61bKUhy4YcDWjiACwNZoDg6/PQgBCNpKxRM5xO8hR7OZTc5pSh+3keX15pFhC8W95gmuR+Txq2VoiuVCi1qQXhO+GZBNcu0yo7OQV/oaaN/k3XAR28SGKwXXi4cZ7UOGkSG6ZOBldGY8+9fLwfUFc/9AaDuuTZ3a51q5YbOaE+A8KGBee7pBIHVK+X4YqSVVEN+nFSZJqQw6l8dZysYIUbkPTjstxVGVDxZUyGujgyQYdusd
  template:
    metadata:
      name: loki-s3-creds
      namespace: loki
