---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup-creds
  namespace: default
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCEZiTm1Mig3yvrfRM28RXExSgwVzuBGOhAiVxwd6ldq7YEIVTF6LMcPEKJhUQK+dd+F1YcFGZbfcQFB0gDiQIKtWGwYtw18NT9cz+pNucPS/ocyvemK5LCg4P14Zhqf0yrbY8RUSgFmk32JhtoYGj06xbS+OcSLe4yAbwIazNwDEVKR7TnaPV4tjK1k7CH8O5LQTME9OXcsFKzPV22VyaFeY58BKZ96O8OPfY4SEGlFWAgIfFCncgcRGOk0UrU0a5fzp+JeKWrhOcBKg3ch/gacg9qXVe3IAUysQPLXsrD1MehOHczLhtLV08rJB1Hi/o8vqhoqflKl+GBX6oRTuku1SO3yDIewscPzrmOyE6+kJpFC7jcsC4ulwg/oBhl6IxnKaODjoCIbw6Uyf1UlvzSJBSyicZkVGIPeyXK79h/GUzRKp5Vtv1+z6IZ9FxClhWWLsthoZd64OwsJUH0QOcpCwvTAl8SLwQj4A8LDJ6fJ72O1LuKXOiChCP8zmjQ4i+XdNBpYbGXqlulVHYlPT6APw3l6oz4oZBSkU2iQSWL9t6J0z1USjEvcfuToyZH188bzYLplK+dbiWRe+ezWMS/m86GJN2vnOs13v5zChG/AFjA/6JrIwA7c0P+CkKp0Sx5oFLFrojoQ+hSAg/XGq9JJCiuA+iArTbCk4LTJZFwpmDDB8vp8bEkA+gXsF0rRDQAmkizDXOUe2jsL6rj/GKlboE3RQ==
    ACCESS_SECRET_KEY: AgBdLGTXCrKSvo4SSIzRM/UqGbEc5Zt++qCX9F0eUsk1fLOjMScBpDzGFQELscN4tuinmFXmB8VdokYdyWqAyeE1gk7TpI78YJ+ho6f8SUR2QqARmhqRwXvEd1nWuMbW09cQUqXfgkbC3Vnl2sMNjaFLrFkCDuiKqgA95XjeQqNIA3Yh1gY2QRvsuBEf62Dg72MbOg8M2PwNqnq+QacusYTKcShkts0B1kzRbakBVZoOb704XmXo2S4j+UZWMnxaVnB4fzNePqg60QQubTsgCG4Fh1NsdraSk7dnuG/RbyrPc5b2nC1SYizqK+ILAskVFzEzdti6MDOhFHnaDCeGUuatVtQPS8djm1Zrxh2BljvyxqW+WuxQoVH5kOjZiEEB0wmxsp/6833/7FSSs7AaO5TaEumLwuuJGrToukdLDVeOsJp7RSdcq2JPQBskQv7I2XbzL2YimAUzQwvG5KrbKEeP09KHHTnyc+VaM1787aeX6w3AaBoRkX9dvf6H2vcnl1Q7774Ou1sfZmHF5fp6Cf9qBjyXuTtKfMuwGn9TQHykZ8YgpTZmPlth0johG2yI2/zjTKd6cGGqFt+nXfpKrSsG6jdpUfVGtYQ/1LkQ9t1mzKUjVQxbDJnrgY8wwSU/wd96pZU1rlxAU/VXnyvJJiL/W3tJCmx5Gfhp/1PdlC3hWS+PwHerEAlPq3QUyJpSiY3CnNxWUduse7e8eV1fUfRT+ydHQ1QVm1SHe83ZtCoap09KVurTLJmi
  template:
    metadata:
      name: minio-backup-creds
      namespace: default
