apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: auth
data:
  configuration.yml: |
    theme: 'dark'

    server:
      address: 'tcp://0.0.0.0:9091'

    log:
      level: 'info'

    authentication_backend:
      ldap:
        implementation: 'lldap'
        address: 'ldap://lldap.auth.svc.cluster.local:3890'
        base_dn: 'dc=fivelabs,dc=tech'
        user: 'uid=authelia,ou=people,dc=fivelabs,dc=tech'

    access_control:
      default_policy: 'deny'
      rules:
        - domain: 'auth.fivelabs.tech'
          policy: 'bypass'
        - domain: '*.fivelabs.tech'
          policy: 'one_factor'
        - domain: torrent.fivelabs.tech
          policy: 'one_factor'
          subject:
            - "group:torrent"
    session:
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1M'
      cookies:
        - domain: 'fivelabs.tech'
          authelia_url: 'https://auth.fivelabs.tech'
      redis:
        host: 'valkey.auth.svc.cluster.local'
        port: 6379

    storage:
      postgres:
        address: 'tcp://pg-rw.default.svc.cluster.local:5432'
        database: 'authelia'
        username: 'authelia'

    notifier:
      filesystem:
        filename: '/config/notification.txt'

    identity_providers:
      oidc:
        jwks:
          - key: {{ secret "/secrets/oidc-issuer-key" | mindent 10 "|" | msquote }}
        clients:
          - client_id: 'gitea'
            client_name: 'Gitea'
            client_secret: '$pbkdf2-sha512$310000$EClfihCe1l10HB6fLbU5Pg$ccnWNFWAorCBiE.O8RFXThZbN6GKysnORroRlrT88VDyP7yTiFN1YBmUrsvegJe4COIjzRwDQi3RR.hAtEexfA'
            public: false
            consent_mode: 'implicit'
            authorization_policy: 'one_factor'
            redirect_uris:
              - 'https://gitea.fivelabs.tech/user/oauth2/authelia/callback'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
              - 'groups'
            userinfo_signed_response_alg: 'none'
          - client_id: 'pgadmin'
            client_name: 'pgAdmin'
            client_secret: '$pbkdf2-sha512$310000$SpPa7qvc9.Z4VzvsuTgoUQ$sz2l/SjmmF.TCDWAGu7inWNzlxJT6FtEvefiygVysCpiEYIoezKcCoGHFH21SHx9N4B4xRGDzPvwK9H55iUJYw'
            public: false
            consent_mode: 'implicit'
            authorization_policy: 'one_factor'
            redirect_uris:
              - 'https://pgadmin.fivelabs.tech/oauth2/authorize'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
            response_types:
              - 'code'
            grant_types:
              - 'authorization_code'
            token_endpoint_auth_method: 'client_secret_basic'
            userinfo_signed_response_alg: 'none'
          - client_id: 'nextcloud'
            client_name: 'Nextcloud'
            client_secret: '$pbkdf2-sha512$310000$4B3botWnKIJlW41Pc4kWhg$3uxQFtZBJFFBe8zHi2Mfx/brcsZb4FmSPUQaP2qsLNopbw1rmA/21U/MKLgDDxwcBD6RgNhGPHUFs8.Q8k840A'   # the Digest from above
            public: false
            consent_mode: 'implicit'
            authorization_policy: 'one_factor'
            redirect_uris:
              - 'https://cloud.fivelabs.tech/apps/user_oidc/code'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
              - 'groups'
            userinfo_signed_response_alg: 'none'
            token_endpoint_auth_method: 'client_secret_post'